apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog-container
        image: s223798216/book-catalog:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://s223798216_722_week6_user:u83CvgN3n4ZQKnvpL2amBgBVUiMMyGDl@dpg-crbnjfrtq21c73cl3afg-a.oregon-postgres.render.com/s223798216_722_week6"
        - name: APP_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: NodePort
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001
